# Dockerfile

# Script       : cam-hack
# Author       : karthik
# Github       : https://github.com/karthik-reddy4444
# Email        : maramkarthik21@gmail.com
# Main Language: Shell

# Download and import main images

# Operating system
FROM debian:latest

# Author info
LABEL MAINTAINER="https://github.com/karthik-reddy4444/cam-hack"

# Working directory
WORKDIR /CamHacker/
# Add files 
ADD . /CamHacker

# Installing other packages
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install curl unzip wget -y
RUN apt-get install --no-install-recommends php -y
RUN apt-get clean

# Main command
CMD ["./ch.sh", "--no-update"]

## Wanna run it own? Try following commnads:

## "sudo docker build . -t karthik/camhacker:latest", "sudo docker run --rm -it karthik/pyphisher:latest"

## "sudo docker pull karthik/camhacker", "sudo docker run --rm -it karthik/camhacker"
